plugin_routing:
  modules:
    vcenter_extension_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_about_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_category_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_cluster_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_datastore_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_dns_config:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_drs_group_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_drs_rule_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_dvs_portgroup_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_guest_boot_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_guest_customization_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_guest_disk_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_guest_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_guest_snapshot_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_capability_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_config_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_dns_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_feature_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_firewall_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_ntp_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_package_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_service_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_ssl_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_vmhba_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_host_vmnic_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_local_role_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_local_user_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_portgroup_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_resource_pool_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_tag_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_target_canonical_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_vm_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_vmkernel_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    vmware_vswitch_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
